# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: User-java build

parameters:
- name: succeed
  displayName: Choose true to fail
  type: boolean
  default: false

trigger:
  branches: 
    include:
    - master 
  paths:
    include:
    - apis/user-java/*


pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: '$(System.DefaultWorkingDirectory)/apis/user-java/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

# This job creates a work item, and only runs if the previous job failed
- job: ErrorHandler
  dependsOn: Build
  condition: failed()
  steps: 
  - bash: |
      az boards work-item create \
        --title "Build $(build.buildNumber) failed" \
        --type bug \
        --org $(System.TeamFoundationCollectionUri) \
        --project $(System.TeamProject)
    env: 
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
    displayName: 'Create work item on failure'